# -*- coding: utf-8 -*-
"""Linear Regression .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7BGaVqZjrWmiLAHaEt_08C1x7-nVAQj

## Imports
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

from google.colab import files
uploaded = files.upload()

customers = pd.read_csv('data.txt')

customers.head()

customers.describe()

customers.info()

"""## Data Analysis"""

import seaborn as sns

sns.jointplot(customers['Time on Website' ],customers['Yearly Amount Spent'])

"""** Do the same but with the Time on App column instead. **"""

sns.jointplot(x='Time on App', y='Yearly Amount Spent', data=customers)

"""** Use jointplot to create a 2D hex bin plot comparing Time on App and Length of Membership.**"""

sns.jointplot(x=customers['Time on App'],y=customers['Yearly Amount Spent'],kind='hex',data= customers)

"""**Let's explore these types of relationships across the entire data set **"""

sns.pairplot(customers)

"""**Based off this plot what looks to be the most correlated feature with Yearly Amount Spent?**"""

#Length of Membership

"""**Create a linear model plot (using seaborn's lmplot) of  Yearly Amount Spent vs. Length of Membership. **"""

sns.lmplot(x='Yearly Amount Spent',y ='Length of Membership', data=customers)

"""## Training and Testing Data

Now that we've explored the data a bit, let's go ahead and split the data into training and testing sets.
** Set a variable X equal to the numerical features of the customers and a variable y equal to the "Yearly Amount Spent" column. **
"""

y = customers['Yearly Amount Spent']

X = customers[['Avg. Session Length', 'Time on App','Time on Website', 'Length of Membership']]

"""** Use model_selection.train_test_split from sklearn to split the data into training and testing sets. Set test_size=0.3 and random_state=101**"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

"""## Training the Model

Now its time to train our model on our training data!

** Import LinearRegression from sklearn.linear_model **
"""

from sklearn.linear_model import LinearRegression

"""**Create an instance of a LinearRegression() model named lm.**"""

lm = LinearRegression()

"""** Train/fit lm on the training data.**"""

lm.fit(X_train,y_train)

"""**Print out the coefficients of the model**"""

print('Coefficients: \n', lm.coef_)

"""## Predicting Test Data
Now that we have fit our model, let's evaluate its performance by predicting off the test values!

** Use lm.predict() to predict off the X_test set of the data.**
"""

predictions = lm.predict(X_test)

"""** Create a scatterplot of the real test values versus the predicted values. **"""

plt.scatter(y_test,predictions)
plt.xlabel('Y Test')
plt.ylabel('Predicted Y')

"""## Evaluating the Model

Let's evaluate our model performance by calculating the residual sum of squares and the explained variance score (R^2).

**Calculate the Mean Absolute Error, Mean Squared Error, and the Root Mean Squared Error. **
"""

from sklearn import metrics

print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

"""## Residuals

Let's quickly explore the residuals to make sure everything was okay with our data.

**Plot a histogram of the residuals and make sure it looks normally distributed. Use either seaborn distplot, or just plt.hist().**
"""

sns.distplot((y_test-predictions),bins=50);

"""## Conclusion
We still want to figure out the answer to the original question, do we focus our efforst on mobile app or website development? Or maybe that doesn't even really matter, and Membership Time is what is really important.  Let's see if we can interpret the coefficients at all to get an idea.

** Recreate the dataframe below. **
"""

coeffecients = pd.DataFrame(lm.coef_,X.columns)
coeffecients.columns = ['Coeffecient']
coeffecients